### ISSUE TITLE
Update the pages that have examples of json to embeddar the playground

### ISSUE THREAD

**Issue by luisoliveirazup** [ZupIT/docs-beagle#128]
# Task

Update the API pages that have examples of JSON listed in the TABs named JSON to work as an embeded playground

* This is how it should look

![image](https://user-images.githubusercontent.com/60155378/102631501-9048f900-412c-11eb-8dfb-040c144aac74.png)

### **Step 1:**

* Comment the json example listed inside the TAB 
* Add the TAG `json-playground:confirm.json` as show in line 83 at the pictuew above. This TAG is the name reference for this code example.

### Check the example bellow

```kotlin
<!-- json-playground:confirm.json
 {
  "_beagleComponent_": "beagle:container",
  "children": [
    {
      "_beagleComponent_": "beagle:button",
      "text": "Confirm Example",
      "onPress": [
        {
          "_beagleAction_": "beagle:confirm",
          "title": "Confirm Title",
          "message": "Confirm Message",
          "onPressOk": {
            "_beagleAction_":"beagle:alert",
            "message": "Confirmed"
          }
        }
      ]
    }
  ]
}
-->
```

### **Step 2:**

Add the shortcode `{{% playground file="confirm.json" language="en" %}}` after the commented code and make sure that:

* The playground file should equals the name reference created for this code in step 1, that is `"confirm-en.json"` on this example
* The language this code references for, that is "en" on this example 

## Code result after update 

```kotlin
<!-- json-playground:confirm.json
 {
  "_beagleComponent_": "beagle:container",
  "children": [
    {
      "_beagleComponent_": "beagle:button",
      "text": "Confirm Example",
      "onPress": [
        {
          "_beagleAction_": "beagle:confirm",
          "title": "Confirm Title",
          "message": "Confirm Message",
          "onPressOk": {
            "_beagleAction_":"beagle:alert",
            "message": "Confirmed"
          }
        }
      ]
    }
  ]
}
-->
{{% playground file="confirm.json" language="en" %}}
````

## List of pages to update (mark the component you will work on and open another issue for it): 
- [x] Acessibilidade https://github.com/ZupIT/docs-beagle/issues/161
- [x] Ações
- [x] AddChildren https://github.com/ZupIT/docs-beagle/pull/156
- [x] Alert https://github.com/ZupIT/docs-beagle/pull/156
- [x] Condition https://github.com/ZupIT/docs-beagle/pull/156
- [x] Confirm
- [x] FormLocalAction
- [x] FormRemoteAction
- [x] FormValidation
- [x] Navigate https://github.com/ZupIT/docs-beagle/pull/155
- [x] OpenNativeRoute https://github.com/ZupIT/docs-beagle/pull/155
- [x] OpenExternalURL https://github.com/ZupIT/docs-beagle/pull/155
- [x] PushStack https://github.com/ZupIT/docs-beagle/pull/155
- [x] PushView https://github.com/ZupIT/docs-beagle/pull/155
- [x] PopStack https://github.com/ZupIT/docs-beagle/pull/155
- [x] PopView https://github.com/ZupIT/docs-beagle/pull/155
- [x] PopToView https://github.com/ZupIT/docs-beagle/pull/155
- [x] ResetApplication https://github.com/ZupIT/docs-beagle/pull/155
- [x] ResetStack https://github.com/ZupIT/docs-beagle/pull/155
- [x] Route https://github.com/ZupIT/docs-beagle/pull/155
- [x] Remote https://github.com/ZupIT/docs-beagle/pull/155
- [x] Local https://github.com/ZupIT/docs-beagle/pull/155
- [x] SendRequest https://github.com/ZupIT/docs-beagle/pull/152
- [x] SetContext https://github.com/ZupIT/docs-beagle/pull/152
- [x] SubmitForm
- [x] Analytics (The components listed on this page dont show any behavious when performed on. They merely serve as a code example to list an analytic feature that is not perceptive on the playground interface)
- [x] Componentes ( don't shown any playground code)
- [x] UI ( don't shown any playground code)
- [x] Button
- [x] Image https://github.com/ZupIT/docs-beagle/pull/167
- [x] ImageContentMode https://github.com/ZupIT/docs-beagle/pull/167
- [x] ImagePath https://github.com/ZupIT/docs-beagle/pull/167
- [x] TabBar https://github.com/ZupIT/docs-beagle/pull/167
- [x] TabView https://github.com/ZupIT/docs-beagle/pull/167
- [x] Text https://github.com/ZupIT/docs-beagle/pull/167
- [x] TextInput https://github.com/ZupIT/docs-beagle/pull/167
- [x] WebView https://github.com/ZupIT/docs-beagle/pull/167
- [x] Touchable https://github.com/ZupIT/docs-beagle/pull/168
- [x] Lazy https://github.com/ZupIT/docs-beagle/pull/168
- [x] Layout https://github.com/ZupIT/docs-beagle/pull/159
- [x] Container https://github.com/ZupIT/docs-beagle/pull/159
- [x] ListView https://github.com/ZupIT/docs-beagle/pull/159
- [x] PageView https://github.com/ZupIT/docs-beagle/pull/159
- [x] PageIndicator https://github.com/ZupIT/docs-beagle/pull/159
- [x] ScrollView https://github.com/ZupIT/docs-beagle/pull/159
- [x] Formulários https://github.com/ZupIT/docs-beagle/pull/158
- [x] Form https://github.com/ZupIT/docs-beagle/pull/158
- [x] Validator https://github.com/ZupIT/docs-beagle/pull/158
- [x] Simple Form https://github.com/ZupIT/docs-beagle/pull/158
- [x] Contexto https://github.com/ZupIT/docs-beagle/pull/172
- [x] Contexto Global https://github.com/ZupIT/docs-beagle/pull/173
- [x] Eventos https://github.com/ZupIT/docs-beagle/pull/173
- [x] Screen https://github.com/ZupIT/docs-beagle/pull/174
- [x] Navigation Bar https://github.com/ZupIT/docs-beagle/pull/174
- [x] Safe Area https://github.com/ZupIT/docs-beagle/pull/174
- [x] Screen Request
- [x] Widget https://github.com/ZupIT/docs-beagle/pull/173
